# Generated by Django 3.2.8 on 2021-10-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTitle', models.CharField(max_length=50, verbose_name='Name of an Article')),
                ('aText', models.TextField(verbose_name='Text of an Article')),
                ('pubDate', models.DateTimeField(verbose_name='Date of publication an Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=50, verbose_name='Name of an Author')),
                ('CommentText', models.CharField(max_length=300, verbose_name='Text of a Comment')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
