# Generated by Django 3.2.8 on 2021-10-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tal_artilce_toefl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artilce_toefl',
            new_name='article_toefl',
        ),
    ]
