# Generated by Django 3.2.8 on 2021-10-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_artilce_toefl_article_toefl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_toefl',
            name='article_ptr',
        ),
        migrations.RemoveField(
            model_name='article_unv',
            name='article_ptr',
        ),
        migrations.DeleteModel(
            name='article_tal',
        ),
        migrations.DeleteModel(
            name='article_toefl',
        ),
        migrations.DeleteModel(
            name='article_unv',
        ),
    ]
