# Generated by Django 3.2.8 on 2021-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_unv'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_tal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTitle', models.CharField(max_length=50, verbose_name='Name of an Article')),
                ('aText', models.TextField(verbose_name='Text of an Article')),
                ('pubDate', models.DateTimeField(verbose_name='Date of publication an Article')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='article_toefl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTitle', models.CharField(max_length=50, verbose_name='Name of an Article')),
                ('aText', models.TextField(verbose_name='Text of an Article')),
                ('pubDate', models.DateTimeField(verbose_name='Date of publication an Article')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
