# Generated by Django 3.2.8 on 2021-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20211031_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_tal',
            name='link',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of an Article'),
        ),
    ]
