# Generated by Django 3.2.8 on 2021-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_tal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_tal',
            name='link',
            field=models.CharField(max_length=50, verbose_name='Name of an Article'),
        ),
    ]
