# Generated by Django 3.2.8 on 2021-10-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_tal_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_tal',
            name='link',
        ),
    ]
